### ISSUE TITLE
Add "Skip Changelog" label to PR

### ISSUE THREAD

**Issue by JohnathonBowers** [BigSamu/OpenSearch_Change_Set_Create_Action#1]
If a contributor enters a `- skip` line in their PR description, the workflow should add a "Skip Changelog" label to the PR.

**Comment by JohnathonBowers** [comment]
I've manually tested the functionality of these changes, and everything works as expected.

I updated the PR description in our feature branch to just have a "- skip" entry. Below are the logs from the workflow:

<img width="523" alt="Screenshot 2023-12-05 at 6 18 41 PM" src="https://github.com/BigSamu/OpenSearch_Change_Set_Create_Action/assets/109883576/ca84ae82-4f9c-47c2-a27c-56795d930e88">

Next, I updated the PR description by removing the "- skip" entry and adding "- feat: Adds a new feature". Below are the logs from the workflow: 

<img width="523" alt="Screenshot 2023-12-05 at 6 19 00 PM" src="https://github.com/BigSamu/OpenSearch_Change_Set_Create_Action/assets/109883576/80a3f5e4-1a17-42a0-8064-6e6f0aecca74">

Finally, here is a screenshot of the commits generated by each workflow, showing that the "skip-changelog" label was added and removed as expected:

<img width="879" alt="Screenshot 2023-12-05 at 6 16 19 PM" src="https://github.com/BigSamu/OpenSearch_Change_Set_Create_Action/assets/109883576/217a3daf-fb46-45bc-a165-d11d91626338">

**Comment by JohnathonBowers** [comment]
Thanks, @BigSamu ! I've added Issue #12 for the unit tests for this feature.

**Comment by BigSamu** [comment]
@JohnathonBowers, tests for this feature have already been created and are ready for review in PR #16. 

I am closing this issue because the updates done here were made directly in the 'main' branch (no PR associated)
